mainSections = ["posts"]

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 6
  cardView = true

[article]
  showTaxonomies = true
  showCategories = true
  showTags = true

[list]
  showCards = true
  cardView = true
  groupByYear = true
